# Generated by Django 3.1.5 on 2021-01-15 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('NetworkApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalServers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('domain_name', models.CharField(max_length=40)),
                ('is_physical', models.BooleanField(default=True)),
                ('server_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NetworkApp.networks')),
            ],
            options={
                'verbose_name': 'Physical Server',
                'verbose_name_plural': 'Physical Servers',
            },
        ),
        migrations.CreateModel(
            name='VirtualServers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virtual_machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ServerApp.physicalservers')),
            ],
            options={
                'verbose_name': 'Virtual Server',
                'verbose_name_plural': 'Virtual Servers',
            },
        ),
    ]
