# Generated by Django 3.1.5 on 2021-01-15 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='physicalservers',
            options={'verbose_name': 'PhysicalServer', 'verbose_name_plural': 'PhysicalServers'},
        ),
    ]
