# Generated by Django 3.1.5 on 2021-01-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Networks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField()),
                ('mask', models.GenericIPAddressField()),
                ('gw', models.GenericIPAddressField()),
                ('dns', models.GenericIPAddressField()),
            ],
            options={
                'verbose_name': 'Network',
                'verbose_name_plural': 'Networks',
            },
        ),
    ]
